// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqof8GTWlHQmMk2lPRcZMyCgd4WVNK_8M',
    appId: '1:135654089255:web:87bbbbf1515416cc016402',
    messagingSenderId: '135654089255',
    projectId: 'mini-shop-flutter',
    authDomain: 'mini-shop-flutter.firebaseapp.com',
    databaseURL: 'https://mini-shop-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mini-shop-flutter.firebasestorage.app',
    measurementId: 'G-FE4GLXZEDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVaTCKu3UVFuKnaF_n2_nDufJBHAtbUys',
    appId: '1:135654089255:android:138d6e9db571b74b016402',
    messagingSenderId: '135654089255',
    projectId: 'mini-shop-flutter',
    databaseURL: 'https://mini-shop-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mini-shop-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhP5R0uSWtDiggAWXKzqNNqRS4V075YI4',
    appId: '1:135654089255:ios:6b40c475e6e64c04016402',
    messagingSenderId: '135654089255',
    projectId: 'mini-shop-flutter',
    databaseURL: 'https://mini-shop-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mini-shop-flutter.firebasestorage.app',
    iosClientId: '135654089255-hfo6dahu9f9u5t57r9499vh00sdg5cb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhP5R0uSWtDiggAWXKzqNNqRS4V075YI4',
    appId: '1:135654089255:ios:6b40c475e6e64c04016402',
    messagingSenderId: '135654089255',
    projectId: 'mini-shop-flutter',
    databaseURL: 'https://mini-shop-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mini-shop-flutter.firebasestorage.app',
    iosClientId: '135654089255-hfo6dahu9f9u5t57r9499vh00sdg5cb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniShopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqof8GTWlHQmMk2lPRcZMyCgd4WVNK_8M',
    appId: '1:135654089255:web:8132d8cebd47f047016402',
    messagingSenderId: '135654089255',
    projectId: 'mini-shop-flutter',
    authDomain: 'mini-shop-flutter.firebaseapp.com',
    databaseURL: 'https://mini-shop-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mini-shop-flutter.firebasestorage.app',
    measurementId: 'G-56LDM00GTD',
  );
}
